# Generated by Django 5.2 on 2025-04-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='施設名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='連絡先')),
                ('zip', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': 'デイサービス等の施設情報',
                'verbose_name_plural': 'デイサービス等の施設情報一覧',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facility', verbose_name='施設')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者一覧',
                'db_table': 'client_users',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='連絡先')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='api.clientuser', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '利用者の家族',
                'verbose_name_plural': '利用者の家族一覧',
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='連絡先')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facility', verbose_name='施設')),
            ],
            options={
                'verbose_name': 'デイサービス等の職員',
                'verbose_name_plural': 'デイサービス等の職員一覧',
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_transport_datetime', models.DateTimeField(verbose_name='送迎予定時間')),
                ('actual_transport_datetime', models.DateTimeField(verbose_name='変更後の送迎予定時間')),
                ('status', models.IntegerField(choices=[(1, 'Scheduled'), (2, 'Completed'), (3, 'Cancelled')], default=1, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_schedules', to='api.clientuser', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '送迎スケジュール',
                'verbose_name_plural': '送迎スケジュール一覧',
                'db_table': 'transport_schedules',
                'unique_together': {('user', 'scheduled_transport_datetime')},
            },
        ),
    ]
