# Generated by Django 5.2 on 2025-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'サービス事業所', 'verbose_name_plural': 'サービス事業所一覧'},
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='facility',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='建物名等'),
        ),
        migrations.AddField(
            model_name='facility',
            name='representative_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='facility',
            name='representative_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='担当者姓'),
        ),
    ]
