# Generated by Django 5.2 on 2025-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通知トークン'),
        ),
    ]
