# Generated by Django 5.2 on 2025-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='name',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='birthday',
            field=models.DateField(default='1950-01-01', verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='first_name_furigana',
            field=models.CharField(blank=True, max_length=255, verbose_name='メイ'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='last_name_furigana',
            field=models.CharField(blank=True, max_length=255, verbose_name='セイ'),
        ),
    ]
