# Generated by Django 5.2 on 2025-05-14 11:40

from django.db import migrations, models

def ensure_email_unique(apps, schema_editor):
    """
    既存ユーザーのメールアドレスが空でないことを確認し、必要に応じて設定します。
    """
    BaseUser = apps.get_model('api', 'BaseUser')

    # メールアドレスが空のユーザーを検索
    empty_email_users = BaseUser.objects.filter(email='')

    for user in empty_email_users:
        # 仮のメールアドレスを設定（運用時は実際のメールを設定する必要あり）
        user.email = f"{user.username}@example.com"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clientuser_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='expo_push_token',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.RunPython(ensure_email_unique),
    ]
