# Generated by Django 5.2 on 2025-04-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_clientuser_name_clientuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportschedule',
            name='actual_transport_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='変更後の送迎予定時間'),
        ),
    ]
